### PR TITLE
enforce interpretation as json to secure the correct interpretation 

### LINKED ISSUE #40: Mattermost: Error on sending
The error:
APPLICATION ERROR #plugin_Slack_ERROR_CURL
The request to Slack didn’t go through. Check your webhook URL. Also make sure there are no unusual characters in your bot name or bot icon settings. Further details may be printed below this box.
Please use the “Back” button in your web browser to return to the previous page. There you can correct whatever problems were identified in this error or select another action. You can also click an option from the menu bar to go directly to a new section.

I cant seem to find something wrong else then a empty UID in the string.
There was a commit 6 days ago in the 1.2 branch that fixes a simular issue.
90406927fd6e022af2d7d900b1d2e67c5d86bf8d

### PR DESCRIPTION
**Pull request by secustor**
fixes #40 on master

### CODE REVIEW

File: Slack.php [hunk 1]
```diff
@@ -290,8 +290,9 @@ function notify($msg, $webhook, $channel, $attachment = FALSE) {
         }
         if ($attachment) {
             $payload['attachments'] = array($attachment);
-        }
+	}
```
Comment (infojunkie) [inline Slack.php]: Plz be careful not to change formatting for no reason
